### ISSUE TITLE
can this game be ported to PS4 ? 

### ISSUE THREAD

**Issue by ssarfaty** [hotshotz79/PS5-Activity-Log#2]
what would it take to port this game to ps4 ? is it that different ? it's a pc with a gpu .. should only adopt some sdk interfaces no ?

**Comment by hotshotz79** [comment]
I think in order to create a homebrew app on PS4, I would have to learn C/C++ ... That's probably the reason why I decided to make a PC app because I only know C#, JavaScriptOn Nov 14, 2024 5:56 a.m., ssarfaty ***@***.***> wrote:
what would it take to port this game to ps4 ? is it that different ? it's a pc with a gpu .. should only adopt some sdk interfaces no ?
